In [62]:
import pandas as pd
import numpy as np

In [68]:
data = pd.read_csv('Data.csv') # import the data
data

# check for NULL values and if there are NULL values print the quantity
if not data.isnull().values.any():
    print('No NULL values')
else:
    cnt = data.isnull().sum()
    print('Number of NULL values: ' + str(cnt))

No NULL values

In [69]:
training = []
testing = []

KeyError: 0

In [64]:
# seperate independent and dependent varibles
iData = data[['area','bedrooms','bathrooms','stories','mainroad','guestroom','basement',
              'hotwaterheating','airconditioning','parking','prefarea','furnishingstatus'
             ]].values
dData = data[['price']]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [60]:
# clean data 
from sklearn.preprocessing import LabelEncoder
led = LabelEncoder()
iData[:,4] = led.fit_transform(iData[:,4])
iData[:,5] = led.fit_transform(iData[:,5])
iData[:,6] = led.fit_transform(iData[:,6])
iData[:,7] = led.fit_transform(iData[:,7])
iData[:,8] = led.fit_transform(iData[:,8])
iData[:,10] = led.fit_transform(iData[:,10])
iData[:,11] = led.fit_transform(iData[:,11])

In [61]:
iData

array([[7420, 4, 2, ..., 2, 1, 0],
       [8960, 4, 4, ..., 3, 0, 0],
       [9960, 3, 2, ..., 2, 1, 1],
       ...,
       [3620, 2, 1, ..., 0, 0, 2],
       [2910, 3, 1, ..., 0, 0, 0],
       [3850, 3, 1, ..., 0, 0, 2]], dtype=object)